# Generated by Django 3.2.25 on 2024-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmodel',
            name='tourn_alias',
            field=models.CharField(default='', max_length=255),
        ),
    ]
