# Generated by Django 4.2.9 on 2024-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_user',
            field=models.ManyToManyField(blank=True, to='transchat.user'),
        ),
    ]
