# Generated by Django 5.0.2 on 2024-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transchat', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='transchat.user'),
        ),
    ]
