# Generated by Django 4.2.9 on 2024-02-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transchat', '0002_user_allowed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allowed_user',
            new_name='blocked_user',
        ),
    ]
