# Generated by Django 3.2.24 on 2024-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transchat', '0003_rename_allowed_user_user_blocked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, to='transchat.User'),
        ),
    ]
