# Generated by Django 3.2.24 on 2024-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transchat', '0004_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
