# Generated by Django 4.2.9 on 2024-02-10 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='playersmodel',
            name='secret_2fa',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 12, 49, 10, 776978, tzinfo=datetime.timezone.utc)),
        ),
    ]
