# Generated by Django 5.0.2 on 2024-02-19 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 13, 54, 32, 167169, tzinfo=datetime.timezone.utc)),
        ),
    ]
