# Generated by Django 4.2.9 on 2024-02-01 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 14, 3, 24, 777205, tzinfo=datetime.timezone.utc)),
        ),
    ]
