# Generated by Django 3.2.24 on 2024-02-09 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20240209_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 12, 33, 48, 119166, tzinfo=utc)),
        ),
    ]
