# Generated by Django 3.2.12 on 2024-01-13 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_roomsmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 20, 7, 23, 849451, tzinfo=utc)),
        ),
    ]
