# Generated by Django 4.2.9 on 2024-02-13 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 11, 29, 11, 533188, tzinfo=datetime.timezone.utc)),
        ),
    ]
