# Generated by Django 5.0.2 on 2024-02-19 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 22, 59, 433627, tzinfo=datetime.timezone.utc)),
        ),
    ]
