# Generated by Django 3.2.24 on 2024-02-14 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroommodel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tournamentroommodel',
            name='tournament',
        ),
        migrations.RenameField(
            model_name='tournamentmodel',
            old_name='game_type',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 14, 28, 30, 77634, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.playersmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 13, 43, 30, 77051, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TournamentPlayerModel',
        ),
        migrations.DeleteModel(
            name='TournamentRoomModel',
        ),
    ]
