# Generated by Django 3.2.12 on 2024-01-14 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20240114_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 10, 6, 55, 961967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
