# Generated by Django 5.0.2 on 2024-02-20 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 14, 41, 36, 197311, tzinfo=datetime.timezone.utc)),
        ),
    ]
