# Generated by Django 3.2.12 on 2024-01-14 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20240114_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serve', to='game.playersmodel'),
        ),
        migrations.AlterField(
            model_name='playerroommodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 16, 5, 40, 166684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own', to='game.playersmodel'),
        ),
    ]
