# Generated by Django 4.2.9 on 2024-02-21 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 12, 37, 14, 201499, tzinfo=datetime.timezone.utc)),
        ),
    ]
