# Generated by Django 3.2.12 on 2024-01-14 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersmodel',
            name='x',
        ),
        migrations.RemoveField(
            model_name='playersmodel',
            name='y',
        ),
        migrations.AddField(
            model_name='playerroommodel',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerroommodel',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 21, 39, 48, 22915, tzinfo=utc)),
        ),
    ]
