# Generated by Django 3.2.24 on 2024-02-19 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20240215_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 5, 52, 924774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 50, 52, 925455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
