# Generated by Django 3.2.12 on 2024-01-15 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20240114_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodel',
            name='nplayers',
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 10, 45, 0, 974362, tzinfo=utc)),
        ),
    ]
