# Generated by Django 3.2.24 on 2024-02-19 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20240219_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersmodel',
            name='session_token',
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 7, 40, 804792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 52, 40, 805502, tzinfo=utc)),
        ),
    ]
