# Generated by Django 3.2.12 on 2024-01-15 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20240115_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playersmodel',
            name='session_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 10, 47, 14, 930343, tzinfo=utc)),
        ),
    ]
