# Generated by Django 3.2.12 on 2024-01-15 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20240115_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='dx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 17, 53, 34, 76970, tzinfo=utc)),
        ),
    ]
