# Generated by Django 3.2.24 on 2024-02-19 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20240219_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 28, 19, 616939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 16, 13, 19, 617591, tzinfo=utc)),
        ),
    ]
