# Generated by Django 3.2.24 on 2024-02-19 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20240219_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 29, 14, 616783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 16, 14, 14, 617366, tzinfo=utc)),
        ),
    ]
