# Generated by Django 3.2.12 on 2024-01-15 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20240115_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodel',
            name='dx',
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 17, 56, 8, 116914, tzinfo=utc)),
        ),
    ]
