# Generated by Django 3.2.12 on 2024-01-15 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20240115_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 20, 14, 56, 453650, tzinfo=utc)),
        ),
    ]
