# Generated by Django 3.2.12 on 2024-01-16 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20240115_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerroommodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 16, 51, 12, 324393, tzinfo=utc)),
        ),
    ]
