# Generated by Django 3.2.24 on 2024-02-19 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20240219_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 15, 41, 44, 589331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 16, 26, 44, 590007, tzinfo=utc)),
        ),
    ]
