# Generated by Django 3.2.12 on 2024-01-17 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_roomsmodel_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodel',
            name='score0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='score1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 20, 14, 27, 70311, tzinfo=utc)),
        ),
    ]
