# Generated by Django 3.2.24 on 2024-02-20 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20240220_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersmodel',
            name='token',
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 10, 54, 54, 891073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 11, 39, 54, 892196, tzinfo=utc)),
        ),
    ]
