# Generated by Django 3.2.24 on 2024-02-21 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_auto_20240221_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments', to='game.PlayersModel'),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 28, 19, 429833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='expires',
            field=models.DateTimeField(default=game.models.default_expires),
        ),
        migrations.CreateModel(
            name='TournamentRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.roomsmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournamentmodel')),
            ],
        ),
    ]
