# Generated by Django 3.2.24 on 2024-02-23 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_auto_20240223_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 15, 8, 18, 360249, tzinfo=utc)),
        ),
    ]
