# Generated by Django 3.2.24 on 2024-02-24 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_auto_20240224_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 11, 55, 31, 794834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentroomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 11, 55, 31, 796780, tzinfo=utc)),
        ),
    ]
