# Generated by Django 3.2.24 on 2024-02-24 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_auto_20240224_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 13, 26, 48, 148384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentroomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 13, 26, 48, 150290, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TournamentPlayerRoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playersmodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournamentroomsmodel')),
            ],
        ),
    ]
