# Generated by Django 3.2.24 on 2024-02-25 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0068_auto_20240224_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 10, 51, 49, 639630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentroomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 10, 51, 49, 642648, tzinfo=utc)),
        ),
    ]
