# Generated by Django 3.2.24 on 2024-02-25 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0070_auto_20240225_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 12, 13, 48, 31219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentroomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 12, 13, 48, 33110, tzinfo=utc)),
        ),
    ]
