# Generated by Django 3.2.24 on 2024-02-25 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0071_auto_20240225_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentroomsmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tournamentroomsmodel',
            name='server',
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 13, 22, 24, 843216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmatchmodel',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player1', to='game.playersmodel'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchmodel',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player2', to='game.playersmodel'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchmodel',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_room', to='game.roomsmodel'),
        ),
        migrations.AlterField(
            model_name='tournamentmatchmodel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='game.tournamentmodel'),
        ),
        migrations.DeleteModel(
            name='TournamentPlayerRoomModel',
        ),
        migrations.DeleteModel(
            name='TournamentRoomsModel',
        ),
    ]
