# Generated by Django 3.2.24 on 2024-02-25 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0072_auto_20240225_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodel',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 13, 24, 56, 324196, tzinfo=utc)),
        ),
    ]
